# Generated by Django 3.2.23 on 2024-02-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_projects_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='img',
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='img'),
        ),
    ]
