# Generated by Django 3.2.23 on 2024-02-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
