# Generated by Django 3.2.23 on 2024-02-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_projects_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='img',
            field=models.FileField(upload_to='images'),
        ),
    ]
