# Generated by Django 3.2.23 on 2024-05-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20240202_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
